In [1]:
import torch
import torch.nn as nn
import numpy as np

In [2]:
def softmax(x):
    return np.exp(x)/np.sum(np.exp(x), axis=0)

In [3]:
x = np.array([1,2,3],dtype=np.float32)
print(softmax(x))

[0.09003058 0.24472846 0.66524094]


In [10]:
x_t = torch.tensor([2.0,1.0,0.1])
print(torch.softmax(x_t,dim=0))

tensor([0.6590, 0.2424, 0.0986])


In [13]:
def cross_entropy(groundtruth, predicted):
    loss = -np.sum(groundtruth * np.log(predicted))
    return loss

In [14]:
Y = np.array([1,0,0])
Y_pred_good = np.array([0.8,0.1,0.1])
Y_pred_bad = np.array([0.3,0.4,0.3])
print(cross_entropy(Y,Y_pred_good))
print(cross_entropy(Y,Y_pred_bad))

0.2231435513142097
1.2039728043259361


In [15]:
#using pytorch

In [17]:
loss = nn.CrossEntropyLoss()

Y=torch.tensor([0])
Y_pred_good = torch.tensor([[2.0,1.0,0.1]])
Y_pred_bad = torch.tensor([[0.5,2.0,0.3]])

print(loss(Y_pred_good,Y))
print(loss(Y_pred_bad,Y))


_, predictions1 = torch.max(Y_pred_good,1)
_, predictions2 = torch.max(Y_pred_bad,1)
print(predictions1)
print(predictions2)

tensor(0.4170)
tensor(1.8406)
tensor([0])
tensor([1])


In [19]:
loss = nn.CrossEntropyLoss()

Y = torch.tensor([2,1,0])
Y_pred_good = torch.tensor([[0.2,1.0,2.1],[2.0,1.0,0.1],[2.0,1.0,0.1]])
Y_pred_bad = torch.tensor([[0.5,2.0,0.3],[2.0,1.0,0.1],[2.0,1.0,0.1]])

print(loss(Y_pred_good,Y))
print(loss(Y_pred_bad,Y))


_, predictions1 = torch.max(Y_pred_good,1)
_, predictions2 = torch.max(Y_pred_bad,1)
print(predictions1)
print(predictions2)

tensor(0.7426)
tensor(1.2916)
tensor([2, 0, 0])
tensor([1, 0, 0])
